<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{ca05b973-c3bc-4b90-a235-a0d338b80144}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	iA: INT;
	iB: INT;
	iC: INT;
	
	fb_add1: FB_Add;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ fb_add1(iIn1:= iA, iIn2:= iB, iOut=> iC);]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>